# Generated by Django 3.2.7 on 2021-10-03 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210930_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='yt_video_url',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name='Youtube Video Url.'),
        ),
    ]
